version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    container_name: bot-server
    ports:
      - "8443:8443"
    env_file:
      - .env 
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
